# Generated by Django 4.1.7 on 2023-05-14 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.IntegerField(db_column='id_cli', primary_key=True, serialize=False)),
                ('rut_cli', models.CharField(db_column='rut_cli', max_length=10)),
                ('nombre_cli', models.CharField(max_length=50)),
                ('apellidop_cli', models.CharField(max_length=50)),
                ('apellidom_cli', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefono_cli', models.CharField(max_length=10)),
                ('sexo_cli', models.CharField(max_length=10)),
                ('direccion_cli', models.CharField(max_length=100)),
                ('estadocivil_cli', models.CharField(max_length=50)),
                ('clave', models.CharField(db_column='clave', max_length=64)),
                ('last_login', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('_is_active', models.BooleanField(db_column='is_active', default=False)),
                ('is_authenticated', models.BooleanField(db_column='is_authenticated', default=False)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
    ]
